apiVersion: v2
description: Helm Chart for Docker example-voting-app
name: example-voting-app
keywords:
- codefresh
- kubernetes
- example-voting-app
type: application
version: 1.0.2
sources:
- https://github.com/garyellis/example-voting-app
maintainers:
- name: Dustin Van Buskirk
  email: dustinvb@codefresh.io
- name: Gary Ellis
  email: gary.luis.ellis@gmail.com
